### ISSUE TITLE
An internal error occurred during: "Stopping GlassFish 4".

### ISSUE THREAD

**Issue by JanneckLange** [Game-Engineering/imao-backend#2]
Dieser Fehler tritt jedes mal beim Stoppen des Glassfish Servers auf.

**Stack trace**
java.util.MissingResourceException: Can't find bundle for base name sun.util.logging.resources.logging, locale de_DE
	at java.base/java.util.ResourceBundle.throwMissingResourceException(Unknown Source)
	at java.base/java.util.ResourceBundle.getBundleImpl(Unknown Source)
	at java.base/java.util.ResourceBundle.getBundleImpl(Unknown Source)
	at java.base/java.util.ResourceBundle.getBundleImpl(Unknown Source)
	at java.base/java.util.ResourceBundle.getBundle(Unknown Source)
	at oracle.eclipse.tools.glassfish.log.LevelResolver.getLocalized(LevelResolver.java:40)
	at oracle.eclipse.tools.glassfish.log.LevelResolver.<init>(LevelResolver.java:22)
	at oracle.eclipse.tools.glassfish.log.AbstractLogFilter.<init>(AbstractLogFilter.java:27)
	at oracle.eclipse.tools.glassfish.log.PatternLogFilterV4.<init>(PatternLogFilterV4.java:23)
	at oracle.eclipse.tools.glassfish.log.AbstractLogFilter.createFilter(AbstractLogFilter.java:66)
	at oracle.eclipse.tools.glassfish.log.GlassfishConsoleManager.getStandardConsole(GlassfishConsoleManager.java:45)
	at oracle.eclipse.tools.glassfish.GlassFishServerBehaviour.stopServer(GlassFishServerBehaviour.java:391)
	at oracle.eclipse.tools.glassfish.GlassFishServerBehaviour.stop(GlassFishServerBehaviour.java:377)
	at org.eclipse.wst.server.core.internal.Server.stopImpl2(Server.java:3698)
	at org.eclipse.wst.server.core.internal.Server.stopImpl(Server.java:3655)
	at org.eclipse.wst.server.core.internal.Server$StopJob.run(Server.java:413)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)

**Session**
eclipse.buildId=4.7.3.M20180301-0715
java.version=9.0.1
java.vendor=Oracle Corporation
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=de_DE
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.java.product

**Comment by JanneckLange** [comment]
Entwicklung wurde eingestellt
